#!/usr/bin/env node
/**
 * update_booking_buttons.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Batch-updates every lady profile page in the /girls directory so that all
 * booking-related <a> buttons link to the cross-page booking flow:
 *
 *   ../booking.html  →  ../booking.html?lady=[identifier]
 *
 * The identifier is derived from the filename (e.g. yuzuki.html → yuzuki).
 *
 * BUTTONS TARGETED (in order of specificity):
 *   1. profile-hero-actions-left  → "Book [Name]"  (desktop hero, top)
 *   2. profile-hero-actions-below → "Book [Name]"  (mobile hero, top)
 *   3. cta-book-btn               → "Book Now"     (bottom CTA section)
 *
 * BUTTONS INTENTIONALLY LEFT UNCHANGED:
 *   • nav-book-now   — site-wide header nav link (not profile-specific)
 *   • Mobile drawer  — generic "Book Now" inside the <nav> element
 *
 * SAFEGUARDS:
 *   • --dry-run flag  : prints a diff-style report without writing any files.
 *   • Already-updated : files that already contain ?lady= for this identifier
 *     are skipped with a [SKIP] notice so the script is safe to re-run.
 *   • Backup option   : pass --backup to write a .bak copy before overwriting.
 *   • No dependencies : uses only Node.js built-ins (fs, path). No npm install
 *     required.
 *
 * USAGE:
 *   node update_booking_buttons.js              # live run
 *   node update_booking_buttons.js --dry-run    # preview only, no writes
 *   node update_booking_buttons.js --backup     # write .bak files first
 * ─────────────────────────────────────────────────────────────────────────────
 */

'use strict';

const fs   = require('fs');
const path = require('path');

// ── Configuration ─────────────────────────────────────────────────────────────

// Path to the girls directory, relative to where this script lives.
const GIRLS_DIR = path.join(__dirname, 'girls');

// The base booking page href that needs the ?lady= param appended.
const BOOKING_BASE = '../booking.html';

// ── CLI flags ─────────────────────────────────────────────────────────────────

const DRY_RUN = process.argv.includes('--dry-run');
const BACKUP  = process.argv.includes('--backup');

if (DRY_RUN) {
  console.log('');
  console.log('╔══════════════════════════════════════════════════════════════╗');
  console.log('║  DRY RUN — no files will be written                         ║');
  console.log('╚══════════════════════════════════════════════════════════════╝');
  console.log('');
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * The three regex patterns that match booking buttons we want to update.
 *
 * Each pattern targets only the href attribute on buttons that:
 *   (a) sit inside a known structural container (class-based), OR
 *   (b) carry the cta-book-btn class.
 *
 * Crucially, the nav-book-now class is NOT matched, so the site-wide
 * header and drawer "Book Now" links are never touched.
 *
 * Strategy: rather than parsing HTML with a full DOM parser (which would
 * require an npm dependency), we use targeted regex patterns that match
 * the exact, consistent markup generated by the profile template. The
 * audit confirmed every file uses identical structure.
 *
 * Each regex captures:
 *   Group 1 — everything before the href value
 *   Group 2 — the href value itself (e.g. "../booking.html")
 *   Group 3 — everything after the href value up to end of tag
 */
const BUTTON_PATTERNS = [
  // ── Pattern A: "Book [Name]" button inside profile-hero-actions-left ──────
  // Matches:  href="../booking.html"  inside the desktop hero action div.
  // Does NOT match nav-book-now because that class appears on the <a> itself,
  // not inside profile-hero-actions-left.
  {
    label: 'hero-actions-left  → Book [Name]',
    // Match any <a> with btn-primary that links to booking.html (no lady= yet)
    // that is NOT a nav-book-now link.
    // We use a two-step approach: replace all bare booking.html hrefs that are
    // NOT on nav-book-now anchors and NOT already parameterised.
    regex: /(class="btn btn-primary"\s+href=")(\.\.\/booking\.html)(")/g,
  },
  // ── Pattern B: cta-book-btn "Book Now" at the bottom of the page ──────────
  {
    label: 'cta-book-btn       → Book Now',
    regex: /(class="btn btn-primary cta-book-btn"\s+href=")(\.\.\/booking\.html)(")/g,
  },
];

// nav-book-now pattern — used only to RESTORE any accidental matches.
// We never want to update these.
const NAV_PATTERN = /href="\.\.\/booking\.html"\s+class="nav-book-now btn btn-primary"/g;

// ── Core replacement function ─────────────────────────────────────────────────

/**
 * processFile(filePath)
 *
 * Reads one HTML file, applies all replacements, and writes it back.
 * Returns a summary object for the final report.
 */
function processFile(filePath) {
  const filename   = path.basename(filePath, '.html');  // e.g. "yuzuki"
  const identifier = filename.toLowerCase();             // always lowercase
  const newHref    = `${BOOKING_BASE}?lady=${identifier}`;

  let original = fs.readFileSync(filePath, 'utf8');
  let updated  = original;
  let totalReplacements = 0;

  // ── Guard: skip if this file is already fully updated ────────────────────
  // A file is considered up-to-date if it already contains the correct param
  // for this specific identifier. We check for at least one occurrence.
  if (original.includes(`${BOOKING_BASE}?lady=${identifier}`)) {
    return { file: filename, status: 'SKIP', replacements: 0,
             reason: `Already contains ?lady=${identifier}` };
  }

  // ── Apply replacements ────────────────────────────────────────────────────
  // We process the entire file content with a single targeted regex that
  // replaces href="../booking.html" → href="../booking.html?lady=[id]"
  // on all btn-primary anchors EXCEPT nav-book-now.
  //
  // Approach:
  //   1. Replace ALL bare booking.html hrefs on btn-primary buttons.
  //   2. Then restore any nav-book-now links that were accidentally caught.
  //
  // This two-pass method is simpler and safer than trying to exclude
  // nav-book-now in a single complex negative-lookahead regex.

  // Pass 1 — update all btn-primary booking hrefs
  // Matches: href="../booking.html" on lines containing btn-primary
  // Uses a line-by-line approach for precision.
  const lines = updated.split('\n');
  const processedLines = lines.map(function(line) {
    // Skip lines that are the nav-book-now link — leave them untouched.
    if (line.includes('nav-book-now')) return line;

    // Skip lines that already have the correct param.
    if (line.includes(`booking.html?lady=${identifier}`)) return line;

    // Replace bare booking.html href on this line.
    // The regex matches the href value in both attribute orderings:
    //   href="../booking.html"  (href first)
    //   href="../booking.html"  (same — both orderings use href="...")
    if (line.includes('btn-primary') && line.includes(BOOKING_BASE + '"')) {
      const before = line;
      const after  = line.replace(
        new RegExp(escapeRegex(BOOKING_BASE) + '"', 'g'),
        newHref + '"'
      );
      if (before !== after) totalReplacements++;
      return after;
    }

    return line;
  });

  updated = processedLines.join('\n');

  // ── Dry-run report ────────────────────────────────────────────────────────
  if (DRY_RUN) {
    if (totalReplacements > 0) {
      console.log(`  [DRY-RUN] ${filename}.html — would update ${totalReplacements} href(s) → ?lady=${identifier}`);
    }
    return { file: filename, status: 'DRY-RUN', replacements: totalReplacements };
  }

  // ── Nothing changed ───────────────────────────────────────────────────────
  if (updated === original) {
    return { file: filename, status: 'UNCHANGED', replacements: 0,
             reason: 'No matching bare booking.html hrefs found on btn-primary lines' };
  }

  // ── Write backup if requested ─────────────────────────────────────────────
  if (BACKUP) {
    fs.writeFileSync(filePath + '.bak', original, 'utf8');
  }

  // ── Write updated file ────────────────────────────────────────────────────
  fs.writeFileSync(filePath, updated, 'utf8');

  return { file: filename, status: 'UPDATED', replacements: totalReplacements };
}

// ── Utility: escape special regex characters in a string ─────────────────────
function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main() {
  console.log('');
  console.log('Albany Angels — Booking Button Batch Updater');
  console.log('─────────────────────────────────────────────');
  console.log(`Target directory : ${GIRLS_DIR}`);
  console.log(`Booking base URL : ${BOOKING_BASE}?lady=[identifier]`);
  console.log(`Backup mode      : ${BACKUP  ? 'ON  (writing .bak files)' : 'OFF'}`);
  console.log('');

  // Read all .html files from the girls directory.
  let files;
  try {
    files = fs.readdirSync(GIRLS_DIR)
              .filter(f => f.endsWith('.html'))
              .sort()
              .map(f => path.join(GIRLS_DIR, f));
  } catch (err) {
    console.error(`ERROR: Could not read directory: ${GIRLS_DIR}`);
    console.error(err.message);
    process.exit(1);
  }

  console.log(`Found ${files.length} HTML file(s) to process.\n`);

  const results = files.map(processFile);

  // ── Summary report ────────────────────────────────────────────────────────
  const updated   = results.filter(r => r.status === 'UPDATED');
  const skipped   = results.filter(r => r.status === 'SKIP');
  const unchanged = results.filter(r => r.status === 'UNCHANGED');
  const dryRun    = results.filter(r => r.status === 'DRY-RUN');

  console.log('');
  console.log('─────────────────────────────────────────────');
  console.log('RESULTS');
  console.log('─────────────────────────────────────────────');

  if (updated.length > 0) {
    console.log(`\n✅ UPDATED (${updated.length} files):`);
    updated.forEach(r => console.log(`   ${r.file}.html — ${r.replacements} href(s) updated`));
  }

  if (skipped.length > 0) {
    console.log(`\n⏭  SKIPPED — already up to date (${skipped.length} files):`);
    skipped.forEach(r => console.log(`   ${r.file}.html`));
  }

  if (unchanged.length > 0) {
    console.log(`\n⚠️  UNCHANGED — no matching buttons found (${unchanged.length} files):`);
    unchanged.forEach(r => console.log(`   ${r.file}.html — ${r.reason}`));
  }

  if (dryRun.length > 0) {
    const wouldUpdate = dryRun.filter(r => r.replacements > 0);
    const wouldSkip   = dryRun.filter(r => r.replacements === 0);
    console.log(`\n🔍 DRY-RUN SUMMARY:`);
    console.log(`   Would update : ${wouldUpdate.length} file(s)`);
    console.log(`   Would skip   : ${wouldSkip.length} file(s) (already up to date)`);
    if (wouldUpdate.length > 0) {
      console.log('\n   Files that would be changed:');
      wouldUpdate.forEach(r => console.log(`   ${r.file}.html — ${r.replacements} href(s)`));
    }
    console.log('\n   Run without --dry-run to apply changes.');
  }

  console.log('');
  console.log('─────────────────────────────────────────────');
  if (!DRY_RUN) {
    console.log(`Done. ${updated.length} file(s) updated, ${skipped.length} skipped.`);
    if (updated.length > 0) {
      console.log('');
      console.log('Next steps:');
      console.log('  git add girls/');
      console.log('  git commit -m "feat: add ?lady= param to all profile booking buttons"');
      console.log('  git push origin main');
    }
  }
  console.log('');
}

main();
